apiVersion: v1
kind: Service # 1
metadata:
  name: frontend
spec:
  type: LoadBalancer # 2
  loadBalancerIP: 34.123.18.158 # Change to reserved IP
  ports:
    - port: 5000 # 3
      protocol: TCP # 4
      targetPort: 5000 # 5
  selector: # 6
    app: frontend # 7
