apiVersion: v1
kind: Service
metadata:
  name: spark-namenode
spec:
  selector:
    app: spark-namenode
  type: LoadBalancer
  loadBalancerIP: 34.86.74.223 # Change to reserved IP
  ports:
    - name: web-ui
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: master
      protocol: TCP
      port: 7077
      targetPort: 7077
    - name: master-rest
      protocol: TCP
      port: 6066
      targetPort: 6066

---
apiVersion: v1
kind: Service
metadata:
  name: spark-client
spec:
  selector:
    app: spark-client
  type: LoadBalancer
  ports:
    - port: 5055 # 3
      protocol: TCP # 4
      targetPort: 5055 # 5
