apiVersion: v1
kind: Service              # 1
metadata:
  name: sonarqube
spec:
  type: LoadBalancer       # 2
  loadBalancerIP: 35.184.215.158  # Change to reserved IP
  ports:
  - port: 9000             # 3
    protocol: TCP          # 4
    targetPort: 9000       # 5
  selector:                # 6
    app: sonarqube         # 7